### ISSUE TITLE
TypeLoadException: Method 'get_StaysOpenOnClick'

### ISSUE THREAD

**Issue by workgroupengineering** [amwx/FluentAvalonia#125]
**Describe the bug**

- run `dotnet new -i Avalonia.Templates`
- run `dotnet new avalonia.xplat -o XApp`
- cd XApp
- Open XApp Solution
- Edit App.xaml like this:
  ```xaml
  <Application xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:XApp"
             x:Class="XApp.App"
             xmlns:sty="using:FluentAvalonia.Styling">
    <Application.DataTemplates>
        <local:ViewLocator/>
    </Application.DataTemplates>


    <Application.Styles>
        <sty:FluentAvaloniaTheme />
    </Application.Styles>
  </Application>
  ```

- Run `XApp.Desktop`
- Execption will throw

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 435
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs:line 53
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 57
   at FluentAvalonia.Styling.FluentAvaloniaTheme.Init()
   at FluentAvalonia.Styling.FluentAvaloniaTheme.set_Owner(IResourceHost value)
   at FluentAvalonia.Styling.FluentAvaloniaTheme.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner)
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 292
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 697
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 206
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at XApp.App.!XamlIlPopulate(IServiceProvider , App ) in C:\Source\Repos\XApp\XApp\App.axaml:line 12
   at XApp.App.!XamlIlPopulateTrampoline(App )
   at XApp.App.Initialize() in C:\Source\Repos\XApp\XApp\App.axaml.cs:line 13
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 316
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 180
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at XApp.Desktop.Program.Main(String[] args) in C:\Source\Repos\XApp\XApp.Desktop\Program.cs:line 12

  This exception was originally thrown at this call stack:
    CompiledAvaloniaXaml.!AvaloniaResources.Build:/Styling/Controls/MenuFlyoutItemStyles.axaml(System.IServiceProvider)
    CompiledAvaloniaXaml.!XamlLoader.TryLoad(string)

Inner Exception 1:
TypeLoadException: Method 'get_StaysOpenOnClick' in type 'FluentAvalonia.UI.Controls.MenuFlyoutItem' from assembly 'FluentAvalonia, Version=1.3.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

```

**Screenshots**

**Desktop/Platform (please complete the following information):**
 - OS: ***Windows 10***
 - FluentAvalonia Version: ***1.3.2***
 - Avalonia Version: ***0.10.999-cibuild0019213-beta***

**Additional context**

**Comment by workgroupengineering** [comment]
luentAvalonia Version: 1.3.2 is non compatible with 0.10.999-cibuild0019213-beta.  0.10.999-cibuild0019213-beta add StaysOpenOnClick to IMenuItrm
