### ISSUE TITLE
App crashes when trying to invalidate the current Theme 

### ISSUE THREAD

**Issue by timunie** [amwx/FluentAvalonia#127]
**Describe the bug**
I try to provide a way to invalidate the theme (for example if I want to adapt to the current Theme). I do this by calling the following line of code in my Command:

```c#
AvaloniaLocator.Current.GetService<FluentAvaloniaTheme>().InvalidateThemingFromSystemThemeChanged();
```

this will throw the following exception:

happens on this line for example: https://github.com/amwx/FluentAvalonia/blob/1cb8b27f669fa8e08a370023458fb7588aec0f7b/FluentAvalonia/Styling/Core/FluentAvaloniaTheme.cs#L516

```txt
System.ArgumentException: An item with the same key has already been added. Key: ContentControlThemeFontFamily
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Avalonia.Collections.AvaloniaDictionary`2.Add(TKey key, TValue value) in /_/src/Avalonia.Base/Collections/AvaloniaDictionary.cs:line 107
   at FluentAvalonia.Styling.FluentAvaloniaTheme.ResolveThemeAndInitializeSystemResources() in C:\Users\<UserName>\source\repos\#OSS\FluentAvalonia\FluentAvalonia\Styling\Core\FluentAvaloniaTheme.cs:line 516
   at FluentAvalonia.Styling.FluentAvaloniaTheme.Refresh(String newTheme) in C:\Users\<UserName>\source\repos\#OSS\FluentAvalonia\FluentAvalonia\Styling\Core\FluentAvaloniaTheme.cs:line 386
   at FluentAvalonia.Styling.FluentAvaloniaTheme.InvalidateThemingFromSystemThemeChanged() in C:\Users\<UserName>\source\repos\#OSS\FluentAvalonia\FluentAvalonia\Styling\Core\FluentAvaloniaTheme.cs:line 258
   at FluentAvaloniaSamples.Views.MainView.Button_OnClick(Object sender, RoutedEventArgs e) in C:\Users\<UserName>\source\repos\#OSS\FluentAvalonia\FluentAvaloniaSamples\Views\MainView.axaml.cs:line 370
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 62
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 68
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 167
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Controls.Button.OnClick() in /_/src/Avalonia.Controls/Button.cs:line 312
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in /_/src/Avalonia.Controls/Button.cs:line 357
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e) in /_/src/Avalonia.Input/InputElement.cs:line 223
   at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass2_0`1.<AddClassHandler>g__Adapter|0(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 143
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 92
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 99
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 311
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 177
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 90
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 502
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 520
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30
   at FluentAvalonia.UI.Controls.CoreWindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Users\<UserName>\source\repos\#OSS\FluentAvalonia\FluentAvalonia\UI\Controls\CoreWindow\CoreWindowImpl.cs:line 122
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at FluentAvaloniaSamples.Program.Main(String[] args) in C:\Users\<UserName>\source\repos\#OSS\FluentAvalonia\FluentAvaloniaSamples\Program.cs:line 13
```

**Screenshots**
Not possible

**Desktop/Platform (please complete the following information):**
 - OS: Win 10
 - FluentAvalonia Version latest
 - Avalonia Version 0.10.13

**Additional context**
I have a PR for this here #124

**Comment by amwx** [comment]
IIRC when I re-wrote FluentAvaloniaTheme, I'm pretty sure I intended `ResolveThemeAndInitializeSystemResources` to only be called once at startup. If this is called more than once, it means I messed something up - I think. Let me double check my work here and then decide what the best fix is.

**Comment by timunie** [comment]
Just for clarification: Not you call this function twice, I do it. I force the App to be Light.Blue on startup as this is the companys corporate design. But the user can click a button to switch to his / her preferred system theme. 

Have a great sunday 
Tim
