### ISSUE TITLE
XamlLoadException when calling InvalidateThemingFromSystemThemeChanged

### ISSUE THREAD

**Issue by PhantomGamers** [amwx/FluentAvalonia#145]
**Describe the bug**
When FluentAvalonia.Styling.FluentAvaloniaTheme.InvalidateThemingFromSystemThemeChanged() is called the following exception is thrown:
```
Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for avares://FluentAvalonia/Styling/StylesV2/Resources.axaml (baseUri: avares://SFP_UI/App.axaml), make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 74
   at FluentAvalonia.Styling.FluentAvaloniaTheme.Refresh(String newTheme)
   at FluentAvalonia.Styling.FluentAvaloniaTheme.InvalidateThemingFromSystemThemeChanged()
   at SFP_UI.ViewModels.MainPageViewModel.OnScanCommand() in C:\Users\Phantom\Documents\GitHub\SFP\SFP_UI\ViewModels\MainPageViewModel.cs:line 126
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 278
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at SFP_UI.Program.Main(String[] args) in C:\Users\Phantom\Documents\GitHub\SFP\SFP_UI\Program.cs:line 20
```

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version 1.3.5
 - Avalonia Version 0.10.14

**Additional context**
The repo that I'm using FluentAvalonia with is https://github.com/PhantomGamers/SFP/tree/f17f093a1ebb6cef75b0dd5b8ec6b9292b1feedf and I'm calling:
`Views.MainWindow.Instance.Theme.InvalidateThemingFromSystemThemeChanged();`
right in the beginning of this method which is called by a button press https://github.com/PhantomGamers/SFP/blob/f17f093a1ebb6cef75b0dd5b8ec6b9292b1feedf/SFP_UI/ViewModels/MainPageViewModel.cs#L124

Also just in case it helps anything, my purpose of trying to invoke this method is that I wish to have my app respond to the user's system theme or accent color changing. Maybe there is a better way of accomplishing this, but I thought that method was intended for this purpose.

**Comment by amwx** [comment]
> Also just in case it helps anything, my purpose of trying to invoke this method is that I wish to have my app respond to the user's system theme or accent color changing. Maybe there is a better way of accomplishing this, but I thought that method was intended for this purpose.

You're correct, that's what this method is for. Seems the error here is file path has 'null' in it which is caused by the changes done in #124.
