### ISSUE TITLE
Unable to run the sample app: The Styles already has a owner

### ISSUE THREAD

**Issue by amelkor** [amwx/FluentAvalonia#16]
Just pulled the repo and getting this when trying to run the sample app (using Rider 2021.1.3):
```
System.InvalidOperationException: The Styles already has a owner.
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 230
   at FluentAvalonia.Styling.FluentAvaloniaTheme.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in F:\source\temp\FluentAvalonia\FluentAvalonia\Styling\Core\FluentAvaloniaTheme.cs:line 220
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 289
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 680
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at FluentAvaloniaSamples.App.!XamlIlPopulate(IServiceProvider , App ) in F:\source\temp\FluentAvalonia\FluentAvaloniaSamples\App.axaml:line 22
   at FluentAvaloniaSamples.App.!XamlIlPopulateTrampoline(App )
   at FluentAvaloniaSamples.App.Initialize() in F:\source\temp\FluentAvalonia\FluentAvaloniaSamples\App.axaml.cs:line 13
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 147
   at FluentAvaloniaSamples.Program.Main(String[] args) in F:\source\temp\FluentAvalonia\FluentAvaloniaSamples\Program.cs:line 12
```

Not sure what this could be related to

**Comment by amwx** [comment]
That's definitely odd. I don't use Rider but I'll look into why this is happening. I can't imagine VS and Rider build the solution so differently that this would occur though.

**Comment by amwx** [comment]
I am unable to reproduce this, using VS, Rider, my local source, and pulling from Github, so I really don't know why this is happening. Have you tried re-pulling the source in case something went wrong for some reason. Otherwise, I really don't know.

**Comment by jeanroyce** [comment]
Same here, in both vs2019 and vs2022

![image](https://user-images.githubusercontent.com/8617825/124510718-d43edb00-ddaa-11eb-9c00-ad0577544dd4.png)

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The Styles already has a owner.
  Source=Avalonia.Styling
  StackTrace:
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 230
   at FluentAvalonia.Styling.FluentAvaloniaTheme.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in C:\Users\jeanr\Downloads\FluentAvalonia\FluentAvalonia\Styling\Core\FluentAvaloniaTheme.cs:line 220
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 292
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 683
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 206
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at FluentAvaloniaSamples.App.!XamlIlPopulate(IServiceProvider , App ) in C:\Users\jeanr\Downloads\FluentAvalonia\FluentAvaloniaSamples\App.axaml:line 25
   at FluentAvaloniaSamples.App.!XamlIlPopulateTrampoline(App )
   at FluentAvaloniaSamples.App.Initialize() in C:\Users\jeanr\Downloads\FluentAvalonia\FluentAvaloniaSamples\App.axaml.cs:line 13
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 311
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 180
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at FluentAvaloniaSamples.Program.Main(String[] args) in C:\Users\jeanr\Downloads\FluentAvalonia\FluentAvaloniaSamples\Program.cs:line 12
```

Even in a new solution

```System.InvalidOperationException
  HResult=0x80131509
  Message=The Styles already has a owner.
  Source=Avalonia.Styling
  StackTrace:
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 230
   at FluentAvalonia.Styling.FluentAvaloniaTheme.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner)
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 292
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 683
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 206
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at AvaloniaApplication1.App.!XamlIlPopulate(IServiceProvider , App ) in C:\Users\jeanr\source\repos\AvaloniaApplication1\AvaloniaApplication1\App.axaml:line 9
   at AvaloniaApplication1.App.!XamlIlPopulateTrampoline(App )
   at AvaloniaApplication1.App.Initialize() in C:\Users\jeanr\source\repos\AvaloniaApplication1\AvaloniaApplication1\App.axaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 311
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 180
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at AvaloniaApplication1.Program.Main(String[] args) in C:\Users\jeanr\source\repos\AvaloniaApplication1\AvaloniaApplication1\Program.cs:line 13
```

**Comment by amwx** [comment]
Ok, I think I was finally able to repro this. The app theme defaults to Light mode, and I'm guessing you're both in dark mode for Windows? The FluentAvaloniaTheme is configured to pull the user theme from Windows, if requested (on by default), which is setting the app theme twice on startup and causing issues. If you go into App.axaml and set `DefaultToUserTheme="False"` on the FluentAvaloniaTheme, that *should* stop this from happening, as a temporary fix while I work on an actual fix:

`<sty:FluentAvaloniaTheme ControlsVersion="2" DefaultToUserTheme="False" />`
