### ISSUE TITLE
Lack of cast from Color2 to Color for SystemAccentColor in FluentAvaloniaTheme.cs

### ISSUE THREAD

**Issue by kokoro-aya** [amwx/FluentAvalonia#169]
**Describe the bug**
When I was testing the sample application, the application failed to run with the following error trace:
```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'FluentAvalonia.UI.Media.Color2' to type 'Avalonia.Media.Color'.
   at FluentAvaloniaSamples.ViewModels.MainViewViewModel..ctor() in /Users/user/RiderProjects/FluentAvalonia/FluentAvaloniaSamples/ViewModels/MainViewViewModel.cs:line 25
   at FluentAvaloniaSamples.Views.MainView..ctor() in /Users/user/RiderProjects/FluentAvalonia/FluentAvaloniaSamples/Views/MainView.axaml.cs:line 24
   at FluentAvaloniaSamples.Views.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in /Users/user/RiderProjects/FluentAvalonia/FluentAvaloniaSamples/Views/MainWindow.axaml:line 26
   at FluentAvaloniaSamples.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
...
```

After some debug, it was found out that in L859 in FluentAvaloniaTheme.cs, the "SystemAccentColor" value was binded to `aColor` without a cast to `Color` data type.

**Desktop/Platform (please complete the following information):**
 - OS: macOS Monterey
 - FluentAvalonia Version 1.4.0
 - Avalonia Version 0.10.15

**Additional context**
The problem could be fixed by replacing `aColor` to `(Color) aColor` in L859.

**Comment by amwx** [comment]
Yep, I forgot the cast there. Should now be fixed and included in v1.4.1.
