### ISSUE TITLE
Error with `ForceNativeTitleBarToTheme` on Linux

### ISSUE THREAD

**Issue by Ombrelin** [amwx/FluentAvalonia#173]
**Describe the bug**
Only linux, `ForceNativeTitleBarToTheme` throws the following error : 

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'ntdll.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libntdll.dll: cannot open shared object file: No such file or directory
   at FluentAvalonia.Interop.Win32Interop.RtlGetVersion(OSVERSIONINFOEX& versionInfo)
   at FluentAvalonia.Styling.FluentAvaloniaTheme.ForceNativeTitleBarToTheme(Window w, String theme)
   at PandocGui.App.OnFrameworkInitializationCompleted() in /mnt/c/Users/arsen/git/pandoc-gui/src/PandocGui/App.axaml.cs:line 31
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 186
   at PandocGui.Program.Main(String[] args) in /mnt/c/Users/arsen/git/pandoc-gui/src/PandocGui/Program.cs:line 11
```

**Desktop/Platform (please complete the following information):**
 - OS: Linux Pop!OS
 - FluentAvalonia Version : 1.1.8
 - Avalonia Version : 0.10.11

**Comment by memorydream** [comment]
I think the api renamed as `ForceWin32WindowToTheme` in 3030fff , it only run on Windows
