### ISSUE TITLE
Support Avalonia 11.0

### ISSUE THREAD

**Issue by mysteryx93** [amwx/FluentAvalonia#190]
Trying to upgrade the project to Avalonia 11.0 gives this error on the line `FluentAvaloniaTheme`

```
  App.axaml(10, 10): [XAMLIL] Internal compiler error while transforming node XamlX.Ast.XamlAstXamlPropertyValueNode:
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Avalonia.Visuals, Version=0.10.18.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'
   at XamlX.TypeSystem.CecilTypeSystem.ResolveWrapped(AssemblyNameReference name)
   at XamlX.TypeSystem.CecilTypeSystem.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at XamlX.TypeSystem.CecilTypeSystem.CustomMetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at XamlX.TypeSystem.CecilHelpers.EqualsCore(TypeReference left, TypeReference right)
   at XamlX.TypeSystem.CecilHelpers.Equals(TypeReference left, TypeReference right)
   at XamlX.TypeSystem.CecilHelpers.EqualsCore(TypeReference left, TypeReference right)
   at XamlX.TypeSystem.CecilHelpers.Equals(TypeReference left, TypeReference right)
   at XamlX.TypeSystem.CecilTypeSystem.CecilTypeCache.<>c__DisplayClass6_0.<Get>b__0(CecilType t)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at XamlX.TypeSystem.CecilTypeSystem.CecilTypeCache.Get(TypeReference reference)
   at XamlX.TypeSystem.CecilTypeSystem.Resolve(TypeReference reference)
   at XamlX.TypeSystem.CecilTypeSystem.CecilMethodBase.get_ReturnType()
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlPropertyPathTransformer.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) Line 10, position 10.
```

**Comment by robloo** [comment]
PR #188 is already in progress to close this. There are a few supplemental PRs as well.
