### ISSUE TITLE
the MenuFlyoutInteractionHandler issue

### ISSUE THREAD

**Issue by xingxing21** [amwx/FluentAvalonia#200]
Hi.
I upgraded the 2.0.0-preview1 and faced the MenuFlyoutInteractionHandler issue.

`<Grid>
    <Grid.ContextFlyout>
        <ui:FAMenuFlyout Placement="Right" ShowMode="TransientWithDismissOnPointerMoveAway">
            <ui:MenuFlyoutItem Text="Test1"/>
            <ui:MenuFlyoutItem Text="Test2"/>
            <ui:MenuFlyoutSeparator />
            <ui:MenuFlyoutItem Text="Test3" />
            <ui:MenuFlyoutSeparator />
            <ui:MenuFlyoutSubItem Text="Options">
                <ui:MenuFlyoutItem Text="Option1" />
                <ui:MenuFlyoutItem Text="Option2" />
            </ui:MenuFlyoutSubItem>
            <ui:MenuFlyoutItem Text="Test4">
                <ui:MenuFlyoutItem.Icon>
                    <ui:ImageIcon Source="{SvgImage /Assets/Tests.svg}" />
                 </ui:MenuFlyoutItem.Icon>
            </ui:MenuFlyoutItem>
        </ui:FAMenuFlyout>
    </Grid.ContextFlyout>
</Grid>`

I got the error when I pushed the mouse right button for showing this menu and clicked any place on the Grid control for closing the menu.
`
at FluentAvalonia.UI.Controls.MenuFlyoutInteractionHandler.Detach(IMenu menu)
at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 483
at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 485
at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 407
at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 503
at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 485
at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 407
at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 503
at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 485
at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 407
at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 503
at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 485
at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 407
at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 503
at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 485
at Avalonia.Controls.Control.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Controls/Control.cs:line 407
at Avalonia.Visual.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Visual.cs:line 503
at Avalonia.Input.InputElement.OnDetachedFromVisualTreeCore(VisualTreeAttachmentEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 485
at Avalonia.Controls.TopLevel.HandleClosed() in /_/src/Avalonia.Controls/TopLevel.cs:line 400
at Avalonia.Controls.WindowBase.HandleClosed() in /_/src/Avalonia.Controls/WindowBase.cs:line 215
at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 723
at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30`

OS: Windows 10
Avalonia Version: 11.0.0-preview1
Visual Studio 2022

thanks!

P.S. Could you change the StayOpenOnClick property to public property?

**Comment by amwx** [comment]
Thanks, was able to repro this. Will look into what's going on here
