### ISSUE TITLE
NavigationView Crashes Changing PaneDisplayMode at Runtime

### ISSUE THREAD

**Issue by robloo** [amwx/FluentAvalonia#250]
**Describe the bug**

In any NavigationView control, changing the PaneDisplayMode at runtime after first initialization will cause a crash if the control has content. The reported exception is "The control already has a visual parent." which happens in the measure overrides.

This can be reproduced in the sample app. Just open up DevTools on a NavigationView in the samples page and change the PaneDisplayMode from Left to Top.

The actual crash seems to be occurring inside Avalonia:
`LayoutHelper.MeasureChild(_topNavGrid, availableSize, new Thickness()).Width;`
It isn't obvious to me what is causing the problem. But this may be an upstream issue.

StackTrace
```
   at Avalonia.Visual.ValidateVisualChild(IVisual c)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild(Object content)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Viewbox.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.StackLayout.GetAverageElementSize(Size availableSize, VirtualizingLayoutContext context, StackLayoutState stackLayoutState)
   at Avalonia.Layout.StackLayout.GetAnchorForRealizationRect(Size availableSize, VirtualizingLayoutContext context)
   at Avalonia.Layout.FlowLayoutAlgorithm.GetAnchorIndex(Size availableSize, Boolean isWrapping, Double minItemSpacing, String layoutId)
   at Avalonia.Layout.FlowLayoutAlgorithm.Measure(Size availableSize, VirtualizingLayoutContext context, Boolean isWrapping, Double minItemSpacing, Double lineSpacing, Int32 maxItemsPerLine, ScrollOrientation orientation, Boolean disableVirtualization, String layoutId)
   at Avalonia.Layout.StackLayout.MeasureOverride(VirtualizingLayoutContext context, Size availableSize)
   at Avalonia.Controls.ItemsRepeater.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at FluentAvalonia.UI.Controls.NavigationView.MeasureTopNavigationViewDesiredWidth(Size availableSize) in \\Software\\FluentAvalonia\\FluentAvalonia\\UI\\Controls\\NavigationView\\NavigationView.members.cs:line 311
   at FluentAvalonia.UI.Controls.NavigationView.HandleTopNavigationMeasureOverrideNormal(Size availableSize) in \\Software\\FluentAvalonia\\FluentAvalonia\\UI\\Controls\\NavigationView\\NavigationView.cs:line 2526
   at FluentAvalonia.UI.Controls.NavigationView.HandleTopNavigationMeasureOverride(Size availableSize) in \\Software\\FluentAvalonia\\FluentAvalonia\\UI\\Controls\\NavigationView\\NavigationView.cs:line 2515
   at FluentAvalonia.UI.Controls.NavigationView.MeasureOverride(Size availableSize) in \\FluentAvalonia\\FluentAvalonia\\UI\\Controls\\NavigationView\\NavigationView.cs:line 319
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at FluentAvaloniaSamples.Program.Main(String[] args) in \\FluentAvalonia\\FluentAvaloniaSamples\\Program.cs:line 11"	string
```

**Screenshots**

N/A

**Desktop/Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - FluentAvalonia Version 2.0 preview 4
 - Avalonia Version 11.0 preview 4

**Additional context**

**Comment by amwx** [comment]
This is definitely a regression in the 11.0 changes upstream. It only happens when the NavigationViewItems have an Icon. When switching between Left and Top, each `NavigationViewItemPresenter` undergoes and full re-templating. What seems to be happening is the template from `Left` mode is never fully disconnected (its visual root is null, but the visual tree hierarchy remains) while the template for `Top` is trying to apply. Since the `IconElement`s are just swapped from one ContentPresenter to another, this is crashing since its not technically been disconnected.

I can repro this all the way back to the first v2/11.0 preview, but I have no clue what change upstream caused this

**Comment by robloo** [comment]
Thanks for taking a look. This might be a tricky one. I'll file an issue upstream in Avalonia soon.

**Comment by amwx** [comment]
Went ahead and opened an issue. It seems its the `Viewbox` that's the cause of this

**Comment by robloo** [comment]
@amwx Any concern if this is closed now?

 1. You already worked-around the issue I believe
 2. Switching to IconSource makes it so this situation can't actually happen any more
 3. The root-cause is tracked in upstream Avalonia in the issue you created

Thanks for all the great work here and in preview 5!
