### ISSUE TITLE
CommandBarButton.Command is broken in 2.0.0-preview4

### ISSUE THREAD

**Issue by jhimes144** [amwx/FluentAvalonia#256]
When binding Command to an `ICommand` property on a view model, loading xaml with Command Bar Button fails with an exception deep in Avalonia. The `property` argument in the below location is TemplatedParent, the `target` argument is a weak reference to my view model. Very strange.

**Reproduce Steps:**
Create a view with the command bar, set the Command property to bind to a `ICommand` property on the view model.

**Exception:**
System.InvalidCastException: 'Unable to cast object of type 'FluentAvBug.ViewModelTest' to type 'Avalonia.AvaloniaObject'.'

**Location:**
(Line 16 of Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.PropertyInfoAccessorFactory)

````
public static IPropertyAccessor CreateAvaloniaPropertyAccessor(WeakReference<object> target, IPropertyInfo property)
            => new AvaloniaPropertyAccessor(new WeakReference<AvaloniaObject>((AvaloniaObject)(target.TryGetTarget(out var o) ? o : null)), (AvaloniaProperty)property);
````

**Call Stack:**
````
System.InvalidCastException: Unable to cast object of type 'FluentAvBug.ViewModelTest' to type 'Avalonia.AvaloniaObject'.
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.PropertyInfoAccessorFactory.CreateAvaloniaPropertyAccessor(WeakReference`1 target, IPropertyInfo property) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/PropertyInfoAccessorFactory.cs:line 17
   at Avalonia.Data.Core.PropertyAccessorNode.StartListeningCore(WeakReference`1 reference) in /_/src/Avalonia.Base/Data/Core/PropertyAccessorNode.cs:line 50
   at Avalonia.Data.Core.ExpressionNode.StartListening() in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 147
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 45
   at Avalonia.Data.Core.ExpressionNode.StartListeningCore(WeakReference`1 reference) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 80
   at Avalonia.Data.Core.ExpressionNode.StartListening() in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 147
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 45
   at Avalonia.Data.Core.ExpressionNode.StartListeningCore(WeakReference`1 reference) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 80
   at Avalonia.Data.Core.ExpressionNode.StartListening() in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 147
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 45
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at Avalonia.Data.BindingBase.UpdateSignal.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Markup/Avalonia.Markup/Data/BindingBase.cs:line 277
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 780
   at Avalonia.AvaloniaObject.InheritedPropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, Optional`1 newValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 517
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 790
   at Avalonia.AvaloniaObject.InheritanceParentChanged[T](StyledPropertyBase`1 property, AvaloniaObject oldParent) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 590
   at Avalonia.AvaloniaObject.set_InheritanceParent(AvaloniaObject value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 93
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent) in /_/src/Avalonia.Base/StyledElement.cs:line 445
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate() in /_/src/Avalonia.Controls/Primitives/TemplatedControl.cs:line 289
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 523
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 39
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 594
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 535
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 63
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Primitives/VisualLayerManager.cs:line 133
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 535
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 602
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 535
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 602
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Window.cs:line 878
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) in /_/src/Avalonia.Controls/WindowBase.cs:line 257
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 286
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 184
   at Avalonia.Controls.Window.ShowCore(Window parent) in /_/src/Avalonia.Controls/Window.cs:line 661
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow() in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 129
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 118
   at FluentAvBug.Program.Main(String[] args) in C:\Code\FluentAvBug\FluentAvBug\Program.cs:line 14
````

**Comment by amwx** [comment]
It's a known issue upstream for preview 4: [see this issue](https://github.com/AvaloniaUI/Avalonia/issues/9508)
Closing as its not an issue on my end and should be fixed with the next preview.
