### ISSUE TITLE
System.InvalidCastException using CommandBar with ViewModel

### ISSUE THREAD

**Issue by Winkiller** [amwx/FluentAvalonia#270]
There is an System.InvalidCastException if DataContext of CommandBar is not an avalonia object

if I set DataContext of CommandBar to my View it works but not possible to Bind Command to my ViewModel
as workaround I can use binding to View: DataContext="{Binding ElementName=PointsView}" But in this way you can not use binding to commands in ViewModel

- Windows 10
- FluentAvalonia Version 2.0.0-preview4
 - Avalonia Version 11.0.0-preview4

<details>
  <summary>Exception</summary>
  <p>
`System.InvalidCastException: Unable to cast object of type 'EnergySoft.Storage.StorageCenter.ViewModels.PointsViewModel' to type 'Avalonia.AvaloniaObject'.
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.PropertyInfoAccessorFactory.CreateAvaloniaPropertyAccessor(WeakReference`1 target, IPropertyInfo property) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/PropertyInfoAccessorFactory.cs:line 17
   at Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings.PropertyInfoAccessorPlugin.Start(WeakReference`1 reference, String propertyName) in /_/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/PropertyInfoAccessorPlugin.cs:line 30
   at Avalonia.Data.Core.PropertyAccessorNode.StartListeningCore(WeakReference`1 reference) in /_/src/Avalonia.Base/Data/Core/PropertyAccessorNode.cs:line 50
   at Avalonia.Data.Core.ExpressionNode.StartListening() in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 147
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 45
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value, Boolean notify) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 111
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 97
   at Avalonia.Data.Core.ExpressionNode.StartListeningCore(WeakReference`1 reference) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 80
   at Avalonia.Data.Core.ExpressionNode.StartListening() in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 147
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 45
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value, Boolean notify) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 111
   at Avalonia.Data.Core.ExpressionNode.ValueChanged(Object value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 97
   at Avalonia.Data.Core.ExpressionNode.StartListeningCore(WeakReference`1 reference) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 80
   at Avalonia.Data.Core.ExpressionNode.StartListening() in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 147
   at Avalonia.Data.Core.ExpressionNode.set_Target(WeakReference`1 value) in /_/src/Avalonia.Base/Data/Core/ExpressionNode.cs:line 45
   at Avalonia.Data.Core.ExpressionObserver.<StartRoot>b__33_0(Object x) in /_/src/Avalonia.Base/Data/Core/ExpressionObserver.cs:line 295
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at Avalonia.Reactive.SingleSubscriberObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/SingleSubscriberObservableBase.cs:line 50
   at Avalonia.Data.BindingBase.UpdateSignal.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Markup/Avalonia.Markup/Data/BindingBase.cs:line 279
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 780
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 691
   at Avalonia.AvaloniaObject.InheritedPropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, Optional`1 newValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 517
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 792
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 691
   at Avalonia.AvaloniaObject.InheritanceParentChanged[T](StyledPropertyBase`1 property, AvaloniaObject oldParent) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 590
   at Avalonia.StyledPropertyBase`1.RouteInheritanceParentChanged(AvaloniaObject o, AvaloniaObject oldParent) in /_/src/Avalonia.Base/StyledPropertyBase.cs:line 230
   at Avalonia.AvaloniaObject.set_InheritanceParent(AvaloniaObject value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 93
   at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent) in /_/src/Avalonia.Base/StyledElement.cs:line 445
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate() in /_/src/Avalonia.Controls/Primitives/TemplatedControl.cs:line 289
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 532
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV) in /_/src/Avalonia.Controls/Grid.cs:line 1151
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged) in /_/src/Avalonia.Controls/Grid.cs:line 1006
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV) in /_/src/Avalonia.Controls/Grid.cs:line 969
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint) in /_/src/Avalonia.Controls/Grid.cs:line 449
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 535
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 47
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 594
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 535
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 602
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 535
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 363
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 290
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 250
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 232
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 145
   at Avalonia.Layout.LayoutManager.ExecuteQueuedLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 104
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 256
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 203
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at StorageCenter.Program.Main(String[] args) in C:\Projects\Storage_New\Storage\UI\StorageCenter\Program.cs:line 13`
  </p>
</details>

**Comment by amwx** [comment]
Known issue from upstream in preview 4, which the fix should be in [preview 5](https://github.com/AvaloniaUI/Avalonia/issues/9508). Its an issue with CompiledBinding so I think in the mean time you can just fall back to normal reflection bindings until preview5 is released.
