### ISSUE TITLE
Hidden content Dialog causes crash when you use Tab to navigate on a window

### ISSUE THREAD

**Issue by emmauss** [amwx/FluentAvalonia#28]
When using Tab to navigate, and a content dialog is next to be tested for tabstop, it throws an exception.
```System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Input.KeyboardNavigation.GetIsTabStop(InputElement element) in /_/src/Avalonia.Input/KeyboardNavigation.cs:line 102
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 128
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext() in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 126
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 253
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 263
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 263
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 263
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 263
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 263
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 263
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 263
   at Avalonia.Input.Navigation.TabNavigation.GetFirstInNextContainer(IInputElement element, IInputElement container, NavigationDirection direction) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 263
   at Avalonia.Input.Navigation.TabNavigation.GetNextInTabOrder(IInputElement element, NavigationDirection direction, Boolean outsideElement) in /_/src/Avalonia.Input/Navigation/TabNavigation.cs:line 54
   at Avalonia.Input.KeyboardNavigationHandler.GetNext(IInputElement element, NavigationDirection direction) in /_/src/Avalonia.Input/KeyboardNavigationHandler.cs:line 78
   at Avalonia.Input.KeyboardNavigationHandler.Move(IInputElement element, NavigationDirection direction, KeyModifiers keyModifiers) in /_/src/Avalonia.Input/KeyboardNavigationHandler.cs:line 99
   at Avalonia.Input.KeyboardNavigationHandler.OnKeyDown(Object sender, KeyEventArgs e) in /_/src/Avalonia.Input/KeyboardNavigationHandler.cs:line 123
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 62
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 68
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 167
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/KeyboardDevice.cs:line 229
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 476
   at Avalonia.X11.X11Window.<ScheduleInput>b__120_0() in /_/src/Avalonia.X11/X11Window.cs:line 719
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Threading.Dispatcher.RunJobs() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 69
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at FluentAvaloniaSamples.Program.Main(String[] args) in /home/aa/personal/FluentAvalonia/FluentAvaloniaSamples/Program.cs:line 12```

**Comment by emmauss** [comment]
A workaround is to wrap it in a ContentControl and set IsVisible to false for that control

**Comment by amwx** [comment]
Will be fixed in new update. Still not 100% sure why this was happening since the ContentDialog is set to IsVisible=False by default and shouldn't have been a candidate for tab navigation anyway, but it has been fixed.
