### ISSUE TITLE
Lack of Datagrid styles

### ISSUE THREAD

**Issue by emmauss** [amwx/FluentAvalonia#30]
There's currently no datagrid styles. Because of that, the avalonia default fluent theme must be specified before v2 themes before datagrid can renderer.
There is also a chance switching themes would crash when datagrid is populated in this way. It doesn't occur with only fluent v1 specified.
Exception;
```Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'Avalonia.Thickness'.
   at Avalonia.Data.BindingValue`1.FromUntyped(Object value) in /_/src/Avalonia.Base/Data/BindingValue.cs:line 250
   at Avalonia.Styling.PropertySetterBindingInstance`1.Inner.OnNext(Object value) in /_/src/Avalonia.Styling/Styling/PropertySetterBindingInstance.cs:line 191
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 138
   at Avalonia.StyledElement.NotifyResourcesChanged(ResourcesChangedEventArgs e, Boolean propagate) in /_/src/Avalonia.Styling/StyledElement.cs:line 843
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.Controls.Primitives.TemplatedControl.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Controls/Primitives/TemplatedControl.cs:line 298
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.Controls.Primitives.TemplatedControl.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Controls/Primitives/TemplatedControl.cs:line 298
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.StyledElement.NotifyChildResourcesChanged(ResourcesChangedEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 536
   at Avalonia.Utilities.WeakSubscriptionManager.Subscription`1.OnEvent(Object sender, T eventArgs) in /_/src/Avalonia.Base/Utilities/WeakSubscriptionManager.cs:line 184
   at Avalonia.Controls.ResourceDictionary.Avalonia.Controls.IResourceProvider.RemoveOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Controls/ResourceDictionary.cs:line 174
   at Avalonia.Styling.Styles.Avalonia.Controls.IResourceProvider.RemoveOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 253
   at FluentAvalonia.Styling.FluentAvaloniaTheme.set_RequestedTheme(String value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 152
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Controls.Button.OnClick() in /_/src/Avalonia.Controls/Button.cs:line 307
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 303
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 149
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 34
   at Avalonia.X11.X11Window.<ScheduleInput>b__120_0() in /_/src/Avalonia.X11/X11Window.cs:line 718
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 105```

**Comment by amwx** [comment]
The DataGrid is one of a few controls I've purposely omitted. DataGrid primarily because it's not an official WinUI control and I have no baseline for how it should look in the new styles. However, it looks like the WinUI community toolkit just updated to WinUI 2.6 so I'll see what they did once they officially release that and try to get this in the next release here.

**Comment by nlogozzo** [comment]
Any update on this?

**Comment by amwx** [comment]
> 
> 
> Any update on this?

Yes. I've been busy on other things lately, but I did start on this today, so it'll make the next release:

![image](https://user-images.githubusercontent.com/40413319/134452663-32b3715f-99a9-434a-a2a6-e5c163ff4081.png)

**Comment by nlogozzo** [comment]
Oh looks amazing! Nice job!
