### ISSUE TITLE
TeachingTip Broke In 2.0.0-Preview6

### ISSUE THREAD

**Issue by PhantomGamers** [amwx/FluentAvalonia#335]
**Describe the bug**
After upgrading to FluentAvalonia 2.0 Preview6, TeachingTip produces the following error when IsOpen is set to True:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Styling.ThemeVariant.op_Explicit(ThemeVariant themeVariant) in /_/src/Avalonia.Base/Styling/ThemeVariant.cs:line 113
   at Avalonia.Controls.TopLevel.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Controls/TopLevel.cs:line 457
   at Avalonia.AvaloniaObject.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 649
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change) in /_/src/Avalonia.Base/Animation/Animatable.cs:line 185
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 700
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 219
   at Avalonia.PropertyStore.EffectiveValue`1.SetLocalValueAndRaise(ValueStore owner, StyledProperty`1 property, T value) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 78
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1 property, T value) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 219
   at Avalonia.PropertyStore.LocalValueBindingObserverBase`1.<OnNext>g__Execute|15_0(LocalValueBindingObserverBase`1 instance, BindingValue`1 value) in /_/src/Avalonia.Base/PropertyStore/LocalValueBindingObserverBase.cs:line 100
   at Avalonia.PropertyStore.LocalValueBindingObserverBase`1.OnNext(BindingValue`1 value) in /_/src/Avalonia.Base/PropertyStore/LocalValueBindingObserverBase.cs:line 110
   at Avalonia.Reactive.AvaloniaPropertyBindingObservable`1.Subscribed(IObserver`1 observer, Boolean first) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyBindingObservable.cs:line 44
   at Avalonia.Reactive.LightweightObservableBase`1.Subscribe(IObserver`1 observer) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 66
   at Avalonia.PropertyStore.LocalValueBindingObserverBase`1.Start(IObservable`1 source) in /_/src/Avalonia.Base/PropertyStore/LocalValueBindingObserverBase.cs:line 33
   at Avalonia.PropertyStore.ValueStore.AddBinding[T](StyledProperty`1 property, IObservable`1 source, BindingPriority priority) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 55
   at Avalonia.AvaloniaObject.Bind[T](StyledProperty`1 property, IObservable`1 source, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 489
   at Avalonia.Controls.Primitives.Popup.Open() in /_/src/Avalonia.Controls/Primitives/Popup.cs:line 397
   at Avalonia.Controls.Primitives.Popup.IsOpenChanged(AvaloniaPropertyChangedEventArgs`1 e) in /_/src/Avalonia.Controls/Primitives/Popup.cs:line 672
   at Avalonia.Controls.Primitives.Popup.<>c.<.cctor>b__21_1(Popup x, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/Primitives/Popup.cs:line 134
   at Avalonia.AvaloniaObjectExtensions.ClassHandlerObserver`1.OnNext(AvaloniaPropertyChangedEventArgs value) in /_/src/Avalonia.Base/AvaloniaObjectExtensions.cs:line 389
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Reactive.LightweightSubject`1.OnNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightSubject.cs:line 24
   at Avalonia.AvaloniaProperty`1.NotifyChanged(AvaloniaPropertyChangedEventArgs`1 e) in /_/src/Avalonia.Base/AvaloniaProperty`1.cs:line 66
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 704
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 219
   at Avalonia.PropertyStore.EffectiveValue`1.SetLocalValueAndRaise(ValueStore owner, StyledProperty`1 property, T value) in /_/src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs:line 78
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1 property, T value) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 226
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/PropertyStore/ValueStore.cs:line 196
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 336
   at Avalonia.Controls.Primitives.Popup.set_IsOpen(Boolean value) in /_/src/Avalonia.Controls/Primitives/Popup.cs:line 210
   at FluentAvalonia.UI.Controls.TeachingTip.IsOpenChangedToOpen()
   at FluentAvalonia.UI.Controls.TeachingTip.<OnIsOpenChanged>b__19_0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 267
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 215
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at SFP_UI.Program.Main(String[] args) in C:\Users\username\Documents\GitHub\SFP\SFP_UI\Program.cs:line 20
```

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version 2.0.0-preview6
 - Avalonia Version 11.0.0-preview6

**Additional context**

Working state can be found here: https://github.com/PhantomGamers/SFP/commit/bcfb02e446bd1bc7c50484ad0ce42144bc653bd7
(Works with TeachingTip segment uncommented with IsOpen set to true)

Broken state can be found here: https://github.com/PhantomGamers/SFP/commit/e3274ffc9ef5d86c1520b5783c6334398f263093
(When the TeachingTip segment in `SFP\SFP_UI\Pages\MainPage.axaml` in uncommented and IsOpen is set to True the aforementioned error is produced)

The error is due to themeVariant being null in `Avalonia.Base/Styling/ThemeVariant.cs:113`

**Comment by amwx** [comment]
I think this is fixed in Avalonia's master now. Best workaround I have until the next preview is to turn overlay popups on in the AppBuilder. If this isn't fixed in the next preview, reopen this and we'll go from there.
