### ISSUE TITLE
Localization crash due to reflection on net 8

### ISSUE THREAD

**Issue by emmauss** [amwx/FluentAvalonia#481]
**Describe the bug**
The following crash occurs on net 8-rc 1.
```Unhandled exception. System.TypeInitializationException: The type initializer for 'FluentAvalonia.UI.FALocalizationHelper' threw an exception.
 ---> System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream utf8Json, JsonSerializerOptions options)
   at FluentAvalonia.UI.FALocalizationHelper..ctor()
   at FluentAvalonia.UI.FALocalizationHelper..cctor()
   --- End of inner exception stack trace ---
```
This can be triggered on loading a NavigationView.

**Screenshots**

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version 2.0.1
 - Avalonia Version 11.0.0

**Additional context**
Using dotnet 8.0 RC1

**Comment by crackedmind** [comment]
Workaround for now is set `<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>`

**Comment by zcsizmadia** [comment]
It looks like as soon as .NEt 8 is released, adding net8.0 to the TargetFrameworks would solve this problem. The other workaround might if the app explicitly PackageReference System.Text.Json and force explicitly to use the newer  STJ instead of using STJ 6.0.x
