### ISSUE TITLE
[Bug?] System.DivideByZeroException: 'Attempted to divide by zero.' when opening FAComboBox inside PropertyGrid

### ISSUE THREAD

**Issue by artizzq** [amwx/FluentAvalonia#529]
### Discussed in https://github.com/amwx/FluentAvalonia/discussions/528

<div type='discussions-op-text'>

<sup>Originally posted by **artizzq** February 28, 2024</sup>
I have properties inside PropertyGrid (https://github.com/bodong1987/Avalonia.PropertyGrid) and for choice and setting some properties I use control like FAComboBox.
![image](https://github.com/amwx/FluentAvalonia/assets/56273839/21045894-e6c3-4d57-8ea3-50f16f43fe8c)

When I try to open combobox (any of them inside PropertyGrid) program breaks on exception.
![image](https://github.com/amwx/FluentAvalonia/assets/56273839/ee1962ee-947d-4e5f-9e9d-2cdbfb1d2a6f)

Screencast:
![problem](https://github.com/amwx/FluentAvalonia/assets/56273839/a35b71cf-fafe-46d7-beb6-4b5e544c8180)

XAML
```
					<Grid RowDefinitions="Auto, *, 2, Auto">
						<Panel Grid.Row="0" ...>
                                                              ...
						</Panel>
						<ScrollViewer Grid.Row="1" Name="propertyGridScroll" ScrollChanged="ScrollViewer_ScrollChanged">
							<ct:TestExtendPropertyGrid Name="propertyGrid" SelectedObject="{Binding PropertyGrid_SelectedObject}" AllowFilter="False" ShowTitle="False" VerticalAlignment="Stretch">
							</ct:TestExtendPropertyGrid>
						</ScrollViewer>
						<GridSplitter Grid.Row="2" ... ResizeDirection="Rows" .../>
						<ContentControl Grid.Row="3" ...></ContentControl>
					</Grid>
```

Code (inside Class that inherited AbstractCellEditFactory)
```
        /// <summary>
        /// Handles the new property.
        /// </summary>
        /// <param name="context">The context.</param>
        /// <returns>Control.</returns>
        public override Control HandleNewProperty(PropertyCellContext context)
        {
            var propertyDescriptor = context.Property;
            var target = context.Target;

            var propertyType = propertyDescriptor.PropertyType;
            if (propertyType != typeof(DbFilterConditionSetUI<string>))
            {
                return null;
            }

            var propertyVal = propertyDescriptor.GetValue(target);

            FAComboBox control = new FAComboBox();
            control.MaxDropDownHeight = 100;
            control.SelectionChanged += (sender, args) =>
            {
                control.SelectedItem = null;
            };

            control.HorizontalAlignment = Avalonia.Layout.HorizontalAlignment.Stretch;
            control.AutoScrollToSelectedItem = false;
            control.ItemTemplate = new FuncDataTemplate<CheckedListBoxItem<string>>((obj, _) =>
            {
                if (obj != null)
                {
                    if (obj is CheckedListBoxItem<string>)
                    {
                        CheckBox checkBox = new CheckBox();
                        checkBox.Content = (obj as CheckedListBoxItem<string>).Value.ToString();
                        checkBox.IsChecked = (propertyVal as DbFilterConditionSetUI<string>).Condition.ValueList.Contains((obj as CheckedListBoxItem<string>).Code);

                        checkBox.IsCheckedChanged += (sender, args) =>
                        {
                            if ((bool)checkBox.IsChecked)
                            {
                                (propertyVal as DbFilterConditionSetUI<string>).Condition.ValueList.Add((obj as CheckedListBoxItem<string>).Code);
                                
                            }
                            else
                            {
                                (propertyVal as DbFilterConditionSetUI<string>).Condition.ValueList.Remove((obj as CheckedListBoxItem<string>).Code);

                            }

                            var selectedItems = (propertyVal as DbFilterConditionSetUI<string>).Items.Select(item => (item as CheckedListBoxItem<string>).Value);

                            string selectedValues = string.Join(", ", selectedItems); // Concatenate the selected values

                            control.SelectedItem = null;
                            control.Text = selectedValues;

                            SetAndRaise(context, control, checkBox.DataContext);
                        };

                        return checkBox;
                    }
                    else return null;
                }
                else
                {
                    Label label = new Label();
                    label.Content = (propertyVal as DbFilterConditionSetUI<string>).GetCheckedItemsString();
                    return label;
                };
            });


            control.DropDownOpened += (sender, args) => 
            { 
                if (control.IsEditable)
                {
                    control.IsDropDownOpen = false;
                } else
                {

                }
                
            };

            control.PointerReleased += (sender, args) =>
            {

            };

            control.KeyDown += (sender, args) => 
            { 
                if (args.PhysicalKey == Avalonia.Input.PhysicalKey.Backspace)
                {
                    control.IsEditable = true;
                    AvaloniaList<Visual> vis_child = control.GetVisualChildren() as AvaloniaList<Visual>;
                    var textBox = vis_child[0].GetVisualChildren().Where(x => x.GetType() == typeof(Avalonia.Controls.TextBox)).Select(x => x).FirstOrDefault();
                    if (textBox != null)
                    {
                        (textBox as Avalonia.Controls.TextBox).KeyDown += (sender1, args1) => {
                            if (args1.PhysicalKey == Avalonia.Input.PhysicalKey.Enter)
                            {
                                if (control.IsEditable == true)
                                {
                                    control.IsEditable = false;

                                    foreach (var item in (propertyVal as DbFilterConditionSetUI<string>).SourceItems)
                                    {
                                        (item as CheckedListBoxItem<string>).IsChecked = false;
                                    }
                                    (propertyVal as DbFilterConditionSetUI<string>).Condition.ValueList.Clear();
                                    if (!string.IsNullOrEmpty(control.Text))
                                    {
                                        string[] items = control.Text.Split(", ");
                                        if (items.Length > 0)
                                        {
                                            foreach (string item_ in items)
                                            {
                                                var real_item = (CheckedListBoxItem<string>)(propertyVal as DbFilterConditionSetUI<string>).SourceItems.Where(x => (x as CheckedListBoxItem<string>).Value == item_).Select(x => x).FirstOrDefault();
                                                (propertyVal as DbFilterConditionSetUI<string>).Condition.ValueList.Add(real_item.Code);
                                                real_item.IsChecked = true;
                                            }
                                        }
                                    }
                                    HandlePropertyChanged(context);
                                    control.IsDropDownOpen = false;
                                }

                            }
                        };
                    }
                }
            };

            control.DropDownClosed += (sender, args) =>
            {
                var selectedItems = (propertyVal as DbFilterConditionSetUI<string>).Items.Select(item => (item as CheckedListBoxItem<string>).Value);

                string selectedValues = string.Join(", ", selectedItems); // Concatenate the selected values

                control.SelectedItem = null;
                control.Text = selectedValues;
            };

            control.ItemsSource = (propertyVal as DbFilterConditionSetUI<string>).SourceItems;

            return control;
        }
```

The stack trace is
 ```
at Avalonia.Controls.LayoutTransformControl.ComputeLargestTransformedSize(Size arrangeBounds)
   at Avalonia.Controls.LayoutTransformControl.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Primitives.PopupRoot.MeasureOverride(Size availableSize)
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
   at Avalonia.Controls.WindowBase.Show()
   at Avalonia.Controls.Primitives.Popup.Open()
   at Avalonia.Controls.Primitives.Popup.IsOpenChanged(AvaloniaPropertyChangedEventArgs`1 e)
   at Avalonia.Controls.Primitives.Popup.<>c.<.cctor>b__21_1(Popup x, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaise(ValueStore owner, IValueEntry value, BindingPriority priority)
   at Avalonia.PropertyStore.ValueStore.ReevaluateEffectiveValue(AvaloniaProperty property, EffectiveValue current, IValueEntry changedValueEntry, Boolean ignoreLocalValue)
   at Avalonia.PropertyStore.BindingEntryBase`2.<SetValue>g__Execute|37_0(BindingEntryBase`2 instance, BindingValue`1 value)
   at Avalonia.PropertyStore.BindingEntryBase`2.SetValue(BindingValue`1 value)
   at Avalonia.PropertyStore.BindingEntryBase`2.OnNext(TSource value)
   at Avalonia.Data.TemplateBinding.PublishValue()
   at Avalonia.Data.TemplateBinding.TemplatedParentPropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore owner, StyledProperty`1 property, T value, BindingPriority priority, Boolean isOverriddenCurrentValue, Boolean isCoercedDefaultValue)
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1 property, T value)
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1 property, T value, BindingPriority priority)
   at FluentAvalonia.UI.Controls.FAComboBox.set_IsDropDownOpen(Boolean value)
   at FluentAvalonia.UI.Controls.FAComboBox.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at <censored>.Program.Main(String[] args) in D:\<censored>\<censored>\<censored>\Program.cs:line 8
```

</div>

**Comment by artizzq** [comment]
I noticed same behaviour using plain ComboBox from Avalonia.

**Comment by artizzq** [comment]
Somehow external DLL library I connected on viewmodel init messed up all my control interaction so any action like scrolling, clicking ended up like this.
Problem solved.
