### ISSUE TITLE
'Command bar' crashes on resizing the window after opening the overflow menu

### ISSUE THREAD

**Issue by moomiji** [amwx/FluentAvalonia#565]
**Describe the bug**
- First, open a CommandBar overflow menu
- Second, resize the window to the smallest
- Then, app crash

**Desktop/Platform (please complete the following information):**
 - OS: Windows 11
 - FluentAvalonia Version: master
 - Avalonia Version: 11.1.0-beta1

**Additional context**
```basic
System.ArgumentException
  HResult=0x80070057
  Message=Attempt to call InvalidateArrange on wrong LayoutManager.
  Source=Avalonia.Base
  StackTrace:
   at Avalonia.Layout.LayoutManager.InvalidateArrange(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteArrangePass()
   at Avalonia.Layout.LayoutManager.InnerLayoutPass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Controls.WindowBase.HandleResized(Size clientSize, WindowResizeReason reason)
   at Avalonia.Controls.Window.HandleResized(Size clientSize, WindowResizeReason reason)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProcMessageHandler(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at FluentAvalonia.Interop.Win32Interop.CallWindowProcW(IntPtr lpPrevWndProc, HWND hWnd, UInt32 msg, WPARAM wParam, LPARAM lParam)
   at FluentAvalonia.UI.Windowing.Win32WindowManager.WndProc(HWND hWnd, UInt32 msg, WPARAM wParam, LPARAM lParam) in .\src\FluentAvalonia\UI\Windowing\Win32\Win32WindowManager.cs:line 106
   at FluentAvalonia.UI.Windowing.Win32WindowManager.WndProcStatic(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in .\src\FluentAvalonia\UI\Windowing\Win32\Win32WindowManager.cs:line 410
   at Avalonia.Win32.Interop.UnmanagedMethods.DefWindowProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProcMessageHandler(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at FluentAvalonia.Interop.Win32Interop.CallWindowProcW(IntPtr lpPrevWndProc, HWND hWnd, UInt32 msg, WPARAM wParam, LPARAM lParam)
   at FluentAvalonia.UI.Windowing.Win32WindowManager.WndProc(HWND hWnd, UInt32 msg, WPARAM wParam, LPARAM lParam) in .\src\FluentAvalonia\UI\Windowing\Win32\Win32WindowManager.cs:line 151
   at FluentAvalonia.UI.Windowing.Win32WindowManager.WndProcStatic(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in .\src\FluentAvalonia\UI\Windowing\Win32\Win32WindowManager.cs:line 410

```

**Comment by ossandust** [comment]
Any update on this? The bug can easily be reproduced with the FAControlsGallery sample in the FluentAvalonia solution.

**Comment by dcooperch** [comment]
I found a workaround for this issue by simply closing the secondary menu when resizing the main window.  The OnResized happens before the layout occurs:

```
    /// <summary>
    /// Closes any open CommandBar secondary-command flyouts before the Avalonia layout pass
    /// runs, working around a known FluentAvalonia bug where the secondary popup's controls
    /// can be registered under the wrong <c>LayoutManager</c>, causing
    /// <c>ArgumentException: Attempt to call InvalidateArrange on wrong LayoutManager</c>
    /// whenever the window is resized while the flyout is open.
    /// <para>
    /// <see cref="WindowBase.OnResized"/> fires before <c>LayoutManager.ExecuteLayoutPass</c>
    /// so this is the correct interception point.
    /// </para>
    /// </summary>
    /// <param name="e">Resize event arguments containing new client size and resize reason.</param>
    protected override void OnResized(WindowResizedEventArgs e)
    {
        CloseCommandBarSecondaryFlyouts();
        base.OnResized(e);
    }

    /// <summary>
    /// Closes every CommandBar in the window's visual tree whose secondary-command flyout is
    /// currently open (<see cref="CommandBar.IsOpen"/> is <see langword="true"/> and the bar
    /// has at least one secondary command).  CommandBars that are always open but carry no
    /// secondary commands are intentionally skipped to
    /// avoid interfering with their forced-open state.
    /// </summary>
    private void CloseCommandBarSecondaryFlyouts()
    {
        foreach (var commandBar in this.GetVisualDescendants().OfType<CommandBar>())
        {
            // Only bars that are open AND have secondary commands create a secondary Popup
            // with its own LayoutManager — those are the ones that trigger the bug.
            if (commandBar.IsOpen && commandBar.SecondaryCommands.Count > 0)
            {
                commandBar.IsOpen = false;
            }
        }
    }
```

Note: This fix only addresses the secondary commands, not an overflow of the primary commands.

**Comment by dcooperch** [comment]
Drop the ` commandBar.SecondaryCommands.Count > 0` to fix the overflow case as well
