### ISSUE TITLE
TeachingTip shows an addional white rectangle popup on Linux

### ISSUE THREAD

**Issue by Genteure** [amwx/FluentAvalonia#634]
**Describe the bug**

1. Add `<PropertyGroup><AvaloniaVersion>11.2.0</AvaloniaVersion></PropertyGroup>` to [`FAControlsGallery.Desktop.csproj`](https://github.com/amwx/FluentAvalonia/blob/3ef356a0919afd9859d0a5d420148d611a45f181/samples/FAControlsGallery.Desktop/FAControlsGallery.Desktop.csproj)
2. `dotnet run --project samples/FAControlsGallery.Desktop/FAControlsGallery.Desktop.csproj`
3. Open the page for `TeachingTip` and click button.

**Screenshots**
![image](https://github.com/user-attachments/assets/2a00c46f-3fae-47ca-998b-845f47749fcf)

**Desktop/Platform (please complete the following information):**
 - OS: Ubuntu 24.04 (GNOME, Wayland)
 - FluentAvalonia Version: latest (or 2.2.0), commit 3ef356a0919afd9859d0a5d420148d611a45f181
 - Avalonia Version: 11.2.0 and up

**Additional context**

![image](https://github.com/user-attachments/assets/3d86754b-ec47-4e50-8f26-cd010f4124fe)

`300, 200` seems to be coming from [`Avalonia.X11/X11Window.cs`](https://github.com/AvaloniaUI/Avalonia/blob/07f3ad23e49da9ced46b7a68392e78a150622c35/src/Avalonia.X11/X11Window.cs#L165-L166). This bug seems to be caused by [commit `1cfa82ca`](https://github.com/AvaloniaUI/Avalonia/commit/1cfa82ca576260bd97864a9cf884fe48e3f7cabb) in Avalonia first released in `11.2.0-beta1`.

-----

<details>
<summary>Old incorrect bug description for archival purpose</summary>

**Describe the bug**

1. Change [`TargetFramework` of `FAControlsGallery.Desktop.csproj`](https://github.com/amwx/FluentAvalonia/blob/3ef356a0919afd9859d0a5d420148d611a45f181/samples/FAControlsGallery.Desktop/FAControlsGallery.Desktop.csproj#L4) from `net8.0` to `net9.0`
2. `dotnet run --project samples/FAControlsGallery.Desktop/FAControlsGallery.Desktop.csproj`
3. Open the page for `TeachingTip` and click button.

**Screenshots**
![image](https://github.com/user-attachments/assets/2a00c46f-3fae-47ca-998b-845f47749fcf)

**Desktop/Platform (please complete the following information):**
 - OS: Ubuntu 24.04 (GNOME, Wayland)
 - FluentAvalonia Version: latest (or 2.2.0), commit 3ef356a0919afd9859d0a5d420148d611a45f181
 - Avalonia Version: tested on 11.1.0 and 11.2.2

**Additional context**
Only reproduced on dotnet 9. It works as intended on dotnet 8.

![image](https://github.com/user-attachments/assets/3d86754b-ec47-4e50-8f26-cd010f4124fe)

- On **dotnet 8**: [`_lightDismissIndicatorPopup.Child.Bounds`](https://github.com/amwx/FluentAvalonia/blob/3ef356a0919afd9859d0a5d420148d611a45f181/src/FluentAvalonia/UI/Controls/TeachingTip/TeachingTip.cs#L239) = `{0, 0, 0, 0}`
- On **dotnet 9**: `_lightDismissIndicatorPopup.Child.Bounds` = `{0, 0, 300, 200}`
- On both: `Width` and `Height` are always `NaN`, `DesiredSize` is always `{0, 0}`

`300, 200` seems to be coming from [`Avalonia.X11/X11Window.cs`](https://github.com/AvaloniaUI/Avalonia/blob/07f3ad23e49da9ced46b7a68392e78a150622c35/src/Avalonia.X11/X11Window.cs#L165-L166) but I'm not sure. Also I still have no idea why it behaves differently on dotnet 8 and 9.

</details>

**Comment by Genteure** [comment]
I tested this in a new Avalonia 11.1.0 project without FluentAvalonia and the `Bounds` of the popup is the intended `0,0,0,0`.

It's definitely related to `PlacementTarget` and `AppWindow`. When I change the `PlacementTarget` to `this` (`TeachingTip`) or `null`, it works correctly without explicitly setting the `Panel` size to 0x0.

https://github.com/amwx/FluentAvalonia/blob/3ef356a0919afd9859d0a5d420148d611a45f181/src/FluentAvalonia/UI/Controls/TeachingTip/TeachingTip.cs#L242

Converting #635 to draft for now.

**Comment by Genteure** [comment]
Turns out it has nothing to do with .NET versions, not sure how did I think it's related to dotnet versions. I have updated the issue description. #635 should be a reasonable fix.

**Comment by austinvaness** [comment]
This still happens for me with FluentAvalonia 2.3.0 and Avalonia 11.2.5

**Comment by BrycensRanch** [comment]
Can  confirm it still happens for me on Fedora Linux 43, Avalonia 11.2.6, and FluentAvalonia 2.3.0

**Comment by BrycensRanch** [comment]
Hi! After more testing, you can fix the bug with 

```
        .With(new X11PlatformOptions()
        {
            OverlayPopups = true,
        })
```

in your Program.cs for Avalonia. While you're there, you can make the life of your Linux users a little better by setting the Vulkan renderer as the default. For me, it drastically increased the performance of my region selector. 

```
            RenderingMode = [X11RenderingMode.Vulkan, X11RenderingMode.Egl, X11RenderingMode.Glx, X11RenderingMode.Software],
```

**Comment by Genteure** [comment]
`OverlayPopups = true` is a good workaround but with compromises (all types of overlay will be inside of the window), it would be better if this is fixed, either in FluentAvalonia or even better Avalonia.

I just did some testing again:

- FluentAvalonia indeed still shows 300x200 rectangle on `master` (commit https://github.com/amwx/FluentAvalonia/commit/779784b716ccb10611ec7c5a88d7e41d0afe1544 as of right now)
- In my minimal reproducing project (https://github.com/AvaloniaUI/Avalonia/issues/17843) with Avalonia 11.2.5, the Panel is hidden and has a bounding box of `150, 100, 0, 0`.
- I just realized even when the `Panel` is hidden, the (transparent) popup still has a size of 300x200 and is blocking mouse clicks on the screen.
- Setting `Width` and `Height` directly on `Popup` doesn't set the size of the underlying overlay window either.

@amwx Can you reopen this issue to help keep track of things please, thanks.

I haven't investigated deeper than this but I feel this would require a fix in Avalonia.

**Comment by Genteure** [comment]
Setting the popup width/height to `0, 1` fixes it. Something magical about zeros I guess.

![Image](https://github.com/user-attachments/assets/6a9057e1-eeec-4810-a6b1-f0603bd43a2c)

-----

Simply changing the values in FluentAvalonia here (linked below) to `0, 1` completely breaks something else, causing exception on every tick.

https://github.com/amwx/FluentAvalonia/blob/779784b716ccb10611ec7c5a88d7e41d0afe1544/src/FluentAvalonia/UI/Controls/TeachingTip/TeachingTip.cs#L240-L244

```
[Visual]Exception in render loop: 'System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Monitor.Exit(Object obj)
   at Avalonia.X11.Glx.GlxContext.RestoreContext.Dispose()
   at Avalonia.X11.Glx.GlxGlPlatformSurface.RenderTarget.Session.Dispose()
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSessionCore(Nullable`1 expectedSize)
   at Avalonia.Skia.GlRenderTarget.BeginRenderingSession(PixelSize size)
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContextCore(Nullable`1 expectedPixelSize, Boolean useScaledDrawing, RenderTargetDrawingContextProperties& properties)
   at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(PixelSize expectedPixelSize, RenderTargetDrawingContextProperties& properties)
   at Avalonia.Rendering.Composition.Server.ServerCompositionTarget.Render()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore(Boolean catchExceptions)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderReentrancySafe(Boolean catchExceptions)
   at Avalonia.Rendering.Composition.Server.ServerCompositor.Render(Boolean catchExceptions)
   at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time)' (RenderLoop #40544074)
```

![Image](https://github.com/user-attachments/assets/b10e1800-e1d7-4e34-921d-37be976aa608)

Setting it to `1, 1` works. A small 1x1 white dot will show up, but that's 99.99833333% ( $1 - \frac{1}{200 \times 300}$ ) better than 200x300 😉.

![Image](https://github.com/user-attachments/assets/14123749-aac8-4f65-93a2-f1efcfc7d783)
