### ISSUE TITLE
Error when selecting MenuItens back and forward

### ISSUE THREAD

**Issue by kvalitetskontrollMarkaryd** [amwx/FluentAvalonia#7]
When selecting MenuItems back and forward an error occurs.
I have also tried using code behind and Bindings instead of CompiledBindings, same result.

IDE: Rider
Manjaro
This nuget package (unofficial)

This is how my Test Project set it up.

XAML:
`
<Window x:Class="SomeApp.UI.Views.MainWindow"
        xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:lookups="clr-namespace:SomeApp.UI.Data.Lookups"
        xmlns:controls="clr-namespace:FluentAvalonia.UI.Controls;assembly=FluentAvalonia"
        xmlns:viewModels="clr-namespace:SomeApp.UI.ViewModels"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        Icon="/Assets/avalonia-logo.ico"
        Title="SomeApp"
        x:DataType="viewModels:MainViewModel">

    <Window.Resources>
        <DataTemplate x:Key="NaviItemTemplate" x:DataType="controls:NavigationViewItem">
            <controls:NavigationViewItem MenuItems="{CompiledBinding MenuItems}"
                                         Content="{CompiledBinding Name}"
                                         Tag="{CompiledBinding Tag}" />
        </DataTemplate>
    </Window.Resources>

    <controls:NavigationView Name="NavView"
                             MenuItemTemplate="{StaticResource NaviItemTemplate}"
                             MenuItems="{CompiledBinding MenuItems}"
                             SelectedItem="{CompiledBinding SelectedItem, Mode=TwoWay}">
        <controls:Frame Name="ContentFrame" Margin="5" />
    </controls:NavigationView>
</Window>
`

C#:
`
public MainViewModel()
        {
            MenuItems = new ObservableCollection<NavigationViewItem>();
            
            // Static list with dummy data
            var projects = ProjectLookupDataService.GetProjectLookup();
            var symbol = new SymbolIcon {Symbol = Symbol.Home};
            MenuItems.Clear();

            foreach (var project in projects)
            {
                MenuItems.Add(new NavigationViewItem
                {
                    Name = project.DisplayMember,
                    Icon = symbol,
                    Tag = project.Id,
                    MenuItems = GetSystemNamesByProjectId(project.Id)
                });
            }
        }

private ObservableCollection<NavigationViewItem> GetSystemNamesByProjectId(int projectId)
        {
            var systemNameList = SystemNameLookupDataService.GetSystemNameLookup();
            var systemNames = systemNameList.Where(p => p.ProjectId == projectId);
            var items = new ObservableCollection<NavigationViewItem>();
            var symbol = new SymbolIcon {Symbol = Symbol.Home};

            foreach (var systemName in systemNames)
            {
                items.Add(new NavigationViewItem
                {
                    Name = systemName.DisplayMember,
                    Icon = symbol,
                    Tag = systemName.Id,
                    MenuItems = GetDrawingsBySystemNameId(systemName.Id)
                });
            }
            return items;
        }

        private ObservableCollection<NavigationViewItem> GetDrawingsBySystemNameId(int systemNameId)
        {
            var drawingList = DrawingLookupDataService.GetDrawingLookup();
            var drawings = drawingList.Where(p => p.SystemNameId == systemNameId);
            var items = new ObservableCollection<NavigationViewItem>();
            var symbol = new SymbolIcon {Symbol = Symbol.Home};

            foreach (var drawing in drawings)
            {
                items.Add(new NavigationViewItem
                {
                    Name = drawing.DisplayMember,
                    Icon = symbol,
                    Tag = drawing.Id,
                    MenuItems = new ObservableCollection<NavigationViewItem>()
                });
            }
            return items;
        }
`

Error Message:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at FluentAvalonia.UI.Controls.IndexPath.GetAt(Int32 index)
   at FluentAvalonia.UI.Controls.NavigationView.FindLowestLevelContainerToDisplaySelectionIndicator()
   at FluentAvalonia.UI.Controls.NavigationView.ShowHideChildrenItemsRepeater(NavigationViewItem nvi)
   at FluentAvalonia.UI.Controls.NavigationView.OnNavigationViewItemExpandedPropertyChanged(AvaloniaPropertyChangedEventArgs args)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 138
   at Avalonia.Reactive.AvaloniaPropertyChangedObservable.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyChangedObservable.cs:line 42
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 720
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 632
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 662
   at FluentAvalonia.UI.Controls.NavigationViewItem.set_IsExpanded(Boolean value)
   at FluentAvalonia.UI.Controls.NavigationView.ChangeIsExpandedNavigationViewItem(NavigationViewItem nvi, Boolean isExpanded)
   at FluentAvalonia.UI.Controls.NavigationView.ToggleIsExpandedNavigationViewItem(NavigationViewItem nvi)
   at FluentAvalonia.UI.Controls.NavigationView.OnNavigationViewItemInvoked(NavigationViewItem nvi)
   at FluentAvalonia.UI.Controls.NavigationView.OnNavigationViewItemTapped(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 60
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 66
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 167
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 120
   at Avalonia.Input.Gestures.PointerReleased(RoutedEventArgs ev) in /_/src/Avalonia.Input/Gestures.cs:line 109
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 147
   at Avalonia.Interactivity.RoutedEvent.InvokeRouteFinished(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/RoutedEvent.cs:line 104
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 102
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 120
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 306
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 173
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 86
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 476
   at Avalonia.X11.X11Window.<ScheduleInput>b__120_0() in /_/src/Avalonia.X11/X11Window.cs:line 719
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Threading.Dispatcher.RunJobs() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 69
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 107
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at SomeApp.UI.Program.Main(String[] args) in SomeApp/SomeApp.UI/Program.cs:line 18

**Comment by amwx** [comment]
Looks like you're binding a list of `NavigationViewItem`s to the `NavigationView` and also setting the `MenuItemTemplate` as an NVI as well, which you don't need to do (that ends up putting an NVI inside an NVI, which I think then compete against each other). 

Either bind the collection of NVIs and don't set the `MenuItemTemplate` or create a collection of models representing your 'project' datatype as it looks, bind that to the `NavigationView` and set the `MenuItemTemplate` as you need.

**Comment by kvalitetskontrollMarkaryd** [comment]
Thanks for your reply! Same result with:

`<Window.Resources>
        <DataTemplate x:Key="NaviItemTemplate" x:DataType="lookups:LookupItem">
            <controls:NavigationViewItem MenuItems="{CompiledBinding Items}"
                                         Content="{CompiledBinding DisplayMember}"
                                         Tag="{CompiledBinding ViewName}" />
        </DataTemplate>
    </Window.Resources>

    <controls:NavigationView Name="NavView"
                             MenuItemTemplate="{StaticResource NaviItemTemplate}"
                             MenuItems="{CompiledBinding MenuItems}"
                             SelectedItem="{CompiledBinding SelectedItem, Mode=TwoWay}">
        <controls:Frame Name="ContentFrame" Margin="5" />
    </controls:NavigationView>`

`public class LookupItem
    {
        public int Id { get; set; }
        public string DisplayMember { get; set; }
        public string ViewName { get; set; }
        public ObservableCollection<LookupItem> Items { get; set; }
    }`

`public MainViewModel()
        {
            MenuItems = new ObservableCollection<LookupItem>();
            var projects = ProjectLookupDataService.GetProjectLookupAsync(); // Static list with dummy data
            
            MenuItems.Clear();

            foreach (var project in projects)
            {
                MenuItems.Add(new LookupItem
                {
                    DisplayMember = project.DisplayMember,
                    Id = project.Id,
                    ViewName = "ProjectView",
                    Items = GetSystemNamesByProjectId(project.Id)
                });
            }
        }`

`private ObservableCollection<LookupItem> GetSystemNamesByProjectId(int projectId)
        {
            var systemNameList = SystemNameLookupDataService.GetSystemNameLookupAsync();
            var systemNames = systemNameList.Where(p => p.ProjectId == projectId); // Static list with dummy data
            var items = new ObservableCollection<LookupItem>();

            foreach (var systemName in systemNames)
            {
                items.Add(new LookupItem
                {
                    DisplayMember = systemName.DisplayMember,
                    Id = systemName.Id,
                    ViewName = "SystemNameView",
                    Items = GetDrawingsBySystemNameId(systemName.Id)
                });
            }
            return items;
        }`

`private ObservableCollection<LookupItem> GetDrawingsBySystemNameId(int systemNameId)
        {
            var drawingList = DrawingLookupDataService.GetDrawingLookupAsync();
            var drawings = drawingList.Where(p => p.SystemNameId == systemNameId); // Static list with dummy data
            var items = new ObservableCollection<LookupItem>();

            foreach (var drawing in drawings)
            {
                items.Add(new LookupItem
                {
                    DisplayMember = drawing.DisplayMember,
                    Id = drawing.Id,
                    ViewName = "DrawingView",
                    Items = new ObservableCollection<LookupItem>()
                });
            }
            return items;
        }`

**Comment by kvalitetskontrollMarkaryd** [comment]
Haven't have run to look in to it more until now. Your solution actually works. Error is gone. 
There is another problem but I will post that separately. 
Thanks!
